[build]
  command = "npm run build"
  publish = "AluraFilosoflix/AluraFilosoflix/dist"
  base = "AluraFilosoflix/AluraFilosoflix"

[functions]
  directory = "AluraFilosoflix/AluraFilosoflix/netlify/functions"
